import sys
def build(bld):
    if sys.platform == 'Darwin':
      libcxx = 'c++'
    else:
      libcxx = 'stdc++'

    # Ji: need to disable boost libraries on cluster until staff installs
    bld(features = 'cxx cprogram',
      source = 'cnn.cpp',
      target = 'cnn',
      cflags   = ['-Wall', '-fopenmp'],
      cxxflags = ['-std=c++0x', '-Wall', '-s', '-Ofast', '-mavx', '-fopenmp'],
      lib      = [libcxx, 'tbb'],
      libpath  = ['../', bld.env.TBB_ROOT + '/../lib/intel64/gcc4.4'],
      includes = ['.', '../tiny_cnn', bld.env.BOOST_ROOT, bld.env.TBB_ROOT],
      linkflags=['-fopenmp'])

#    bld(features = 'cxx cprogram',
#      source = 'main.cpp',
#      target = 'main',
#      cflags   = ['-Wall'],
#      cxxflags = ['-std=c++0x', '-Wall', '-s', '-Ofast', '-mavx'],
#      lib      = [libcxx, 'boost_timer-mt', 'tbb'],
#      libpath  = ['../', bld.env.TBB_ROOT + '../lib/intel64/gcc4.4'],
#      includes = ['.', '../tiny_cnn', bld.env.BOOST_ROOT, bld.env.TBB_ROOT])

     # Ji: need to disable opencv on cluster until staff installs
#    bld(features = 'cxx cprogram',
#      source = 'ocr.cpp',
#      target = 'ocr',
#      cflags   = ['-Wall', '-g', '-ggdb'],
#      cxxflags = ['-std=c++0x', '-Wall', '-s', '-Ofast', '-mavx'],
#      lib      = [libcxx, 'opencv_core', 'opencv_highgui', 'opencv_imgproc', 'tbb'],
#      libpath  = ['../', bld.env.TBB_ROOT + '../lib/intel64/gcc4.4', '/share/apps/opencv-gcc-2.4.11/lib'],
#      includes = ['.', '../tiny_cnn', bld.env.BOOST_ROOT, bld.env.TBB_ROOT, '/share/apps/opencv-gcc-2.4.11/include'])
